#!/bin/bash

set -e
set -o pipefail

echo "----------"
echo "GIT POST RECEIVE HOOK"
echo "User: $USER"
echo "Host: $HOSTNAME"
echo "Path: $PWD"

while read oldrev newrev refname
do

    echo "oldrev: $oldrev"
    echo "newrev: $newrev"
    echo "refname: $refname"

    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    echo "Branch: $branch"

    if ! [ "$branch" == "production" ] ; then
      echo "This is not a deployable branch."
      echo "Ending deployment."
      exit 1;
    fi

    revision=$(git rev-parse $branch)
    rev=$(expr substr "${revision}" 1 7)

    echo "revision: $revision"
    echo "rev: $rev"

    cd ../
    echo "Path: $PWD"

    base=$PWD
    repo="$base/repo"
    temp="$base/releases/temp"
    release="$base/releases/$rev"

    echo "base: $base"
    echo "repo: $repo"
    echo "temp: $temp"
    echo "release: $release"

    echo "rm -rf $temp"
    rm -rf $temp

    echo "mkdir $temp"
    mkdir $temp

    echo "git --work-tree=$temp/ --git-dir=$repo/ checkout $branch -f"
    git --work-tree=$temp/ --git-dir=$repo/ checkout $branch -f

    echo "cd $temp"
    cd $temp

    echo "GIT_REVISION=$rev" >> .env

    # echo "nvm install"
    # nvm install

    echo "yarn install"
    yarn install

    echo "ember build -prod"
    ember build -prod

    echo "mkdir $release"
    mkdir $release

    echo "cp -r $temp/dist/* $release"
    cp -r $temp/dist/* $release

    echo "rm -rf $base/current/*"
    rm -rf $base/current/*

    echo "cp -r $release/* $base/current/"
    cp -r $release/* $base/current/

    echo "rm -rf $temp"
    rm -rf $temp
done
echo "----------"
